### ISSUE TITLE
LRU Cache - Misleading documentation 

### ISSUE THREAD

**Issue by arditti** [udger/udger-nodejs#44]
According to the documentation, in order to start using the LRU cache, the following line should be added:
`udgerParser.setCacheEnable()`
While debugging it, and saw it doesn't affect the response nor the response time, I discovered that the following line should be added instead:
`udgerParser.setCacheEnable(true)`

digging into the source-code support my findings:
`/**
     * Activate cache
     * @param {Boolean} cache - true or false
     */
    setCacheEnable(cache) {
        this.cacheEnable = cache;
    }`

**Comment by eviltik** [comment]
Thank you for feedback ! I'll take care of that.

**Comment by eviltik** [comment]
will be in 1.4.0, publishing soon
