### ISSUE TITLE
update better-sqlite3 package version

### ISSUE THREAD

**Issue by henningborchers** [udger/udger-nodejs#45]
Can you please update the better-sqlite3 dependency to version v6.0.1
This  version of better-sqlite3 (v6.0.1) uses prebuilt binaries and resolves many problems with npm install

**Comment by eviltik** [comment]
Sorry for delay. I'll take a look at this in a few days. Actual master branche si broken for now, need to fix that first. Stay tuned.

**Comment by eviltik** [comment]
2 years later ... huhu !

udget-nodejs 1.4.0 now use better-sqlite3 7.5.0.
